using System.Windows;using System.Windows.Controls;using IKDex.Models;using IKDex.Services;
namespace IKDex.Views;
public partial class AttendancePage:UserControl
{
 private readonly AttendanceService _service=new(App.Database);private readonly UserSession _session;private readonly bool _canManage;public event EventHandler? DataChanged;
 public AttendancePage(UserSession session){_session=session;_canManage=new AuthorizationService(session).CanManageEmployees;InitializeComponent();var employees=new EmployeeService(App.Database).GetAll();EmployeeBox.ItemsSource=employees;EmployeeFilter.ItemsSource=employees;MonthPicker.SelectedDate=DateTime.Today;WorkDatePicker.SelectedDate=DateTime.Today;if(!_canManage){var own=employees.FirstOrDefault(x=>x.Id==session.EmployeeId);EmployeeBox.SelectedItem=own;EmployeeFilter.SelectedItem=own;EmployeeBox.IsEnabled=EmployeeFilter.IsEnabled=false;}LoadData();}
 private void LoadData(){var month=MonthPicker.SelectedDate??DateTime.Today;long? employeeId=_canManage?(EmployeeFilter.SelectedValue is long id?id:null):_session.EmployeeId;var rows=_service.GetMonth(month,employeeId);AttendanceGrid.ItemsSource=rows;SummaryText.Text=$"{month:MMMM yyyy} • {rows.Count} günlük kayıt";}
 private void FilterChanged(object sender,SelectionChangedEventArgs e){if(IsLoaded)LoadData();}
 private void AttendanceGrid_SelectionChanged(object sender,SelectionChangedEventArgs e){if(AttendanceGrid.SelectedItem is not AttendanceRecord r)return;EmployeeBox.SelectedValue=r.EmployeeId;WorkDatePicker.SelectedDate=r.WorkDate;CheckInBox.Text=r.CheckIn?.ToString(@"hh\:mm")??"";CheckOutBox.Text=r.CheckOut?.ToString(@"hh\:mm")??"";NoteBox.Text=r.Note;}
 private void Save_Click(object sender,RoutedEventArgs e){if(EmployeeBox.SelectedValue is not long employeeId||WorkDatePicker.SelectedDate is not DateTime date){ShowError("Personel ve tarih seçin.");return;}if(!TryTime(CheckInBox.Text,out var checkIn)||!TryTime(CheckOutBox.Text,out var checkOut)){ShowError("Saatleri 08:30 biçiminde girin.");return;}try{_service.Save(employeeId,date,checkIn,checkOut,NoteBox.Text);MonthPicker.SelectedDate=date;LoadData();ErrorText.Visibility=Visibility.Collapsed;DataChanged?.Invoke(this,EventArgs.Empty);}catch(InvalidOperationException ex){ShowError(ex.Message);}}
 private void NowIn_Click(object sender,RoutedEventArgs e)=>SaveNow(true);private void NowOut_Click(object sender,RoutedEventArgs e)=>SaveNow(false);
 private void SaveNow(bool isCheckIn){if(_session.EmployeeId is not long id){ShowError("Hesabınıza bağlı bir personel kaydı bulunmuyor.");return;}var existing=_service.GetMonth(DateTime.Today,id).FirstOrDefault(x=>x.WorkDate.Date==DateTime.Today);var input=existing?.CheckIn;var output=existing?.CheckOut;if(isCheckIn){if(input is not null){ShowError("Bugün için giriş kaydınız zaten var.");return;}input=DateTime.Now.TimeOfDay;}else{if(input is null){ShowError("Çıkıştan önce giriş yapmalısınız.");return;}output=DateTime.Now.TimeOfDay;}_service.Save(id,DateTime.Today,input,output,existing?.Note??"");LoadData();DataChanged?.Invoke(this,EventArgs.Empty);}
 private static bool TryTime(string text,out TimeSpan? value){if(string.IsNullOrWhiteSpace(text)){value=null;return true;}if(TimeSpan.TryParse(text,out var parsed)&&parsed>=TimeSpan.Zero&&parsed<TimeSpan.FromDays(1)){value=parsed;return true;}value=null;return false;}
 private void ShowError(string message){ErrorText.Text=message;ErrorText.Visibility=Visibility.Visible;}
}
