using Microsoft.Win32;using System.Diagnostics;using System.IO;using System.Windows;using System.Windows.Controls;using IKDex.Models;using IKDex.Services;
namespace IKDex.Views;
public partial class DocumentsPage:UserControl
{
 private readonly DocumentService _service=new(App.Database);private readonly UserSession _session;private readonly bool _canManage;private EmployeeDocument? _selected;
 public DocumentsPage(UserSession session){_session=session;_canManage=new AuthorizationService(session).CanManageEmployees;InitializeComponent();var employees=new EmployeeService(App.Database).GetAll();EmployeeBox.ItemsSource=employees;EmployeeFilter.ItemsSource=employees;if(!_canManage){var own=employees.FirstOrDefault(x=>x.Id==session.EmployeeId);EmployeeBox.SelectedItem=own;EmployeeFilter.SelectedItem=own;EmployeeBox.IsEnabled=EmployeeFilter.IsEnabled=false;}LoadData();}
 private void LoadData(){long? employeeId=_canManage?(EmployeeFilter.SelectedValue is long id?id:null):_session.EmployeeId;var items=_service.GetAll(employeeId,ArchivedCheck.IsChecked==true);DocumentsGrid.ItemsSource=items;SummaryText.Text=$"{items.Count} belge listeleniyor";}
 private void FilterChanged(object sender,RoutedEventArgs e){if(IsLoaded)LoadData();}
 private void New_Click(object sender,RoutedEventArgs e){_selected=null;DocumentsGrid.SelectedItem=null;DisplayNameBox.Clear();FilePathBox.Clear();CategoryBox.SelectedItem=null;ExpiryDatePicker.SelectedDate=null;OpenButton.Visibility=ArchiveButton.Visibility=Visibility.Collapsed;ErrorText.Visibility=Visibility.Collapsed;}
 private void ChooseFile_Click(object sender,RoutedEventArgs e){var d=new OpenFileDialog{Filter="Desteklenen belgeler|*.pdf;*.doc;*.docx;*.xls;*.xlsx;*.png;*.jpg;*.jpeg|Tüm dosyalar|*.*"};if(d.ShowDialog()==true){FilePathBox.Text=d.FileName;if(string.IsNullOrWhiteSpace(DisplayNameBox.Text))DisplayNameBox.Text=Path.GetFileNameWithoutExtension(d.FileName);}}
 private void Save_Click(object sender,RoutedEventArgs e){if(EmployeeBox.SelectedValue is not long employeeId||CategoryBox.SelectedItem is not ComboBoxItem category||string.IsNullOrWhiteSpace(DisplayNameBox.Text)||string.IsNullOrWhiteSpace(FilePathBox.Text)){ShowError("Personel, kategori, belge adı ve dosya zorunludur.");return;}try{_service.Add(employeeId,category.Content.ToString()!,DisplayNameBox.Text,FilePathBox.Text,ExpiryDatePicker.SelectedDate);New_Click(sender,e);LoadData();}catch(Exception ex)when(ex is IOException or InvalidOperationException or UnauthorizedAccessException){ShowError(ex.Message);}}
 private void DocumentsGrid_SelectionChanged(object sender,SelectionChangedEventArgs e){if(DocumentsGrid.SelectedItem is not EmployeeDocument d)return;_selected=d;EmployeeBox.SelectedValue=d.EmployeeId;DisplayNameBox.Text=d.DisplayName;SelectCategory(d.Category);ExpiryDatePicker.SelectedDate=d.ExpiryDate;FilePathBox.Text=d.FileName;OpenButton.Visibility=Visibility.Visible;ArchiveButton.Content=d.IsArchived?"Arşivden çıkar":"Arşivle";ArchiveButton.Visibility=Visibility.Visible;}
 private void Open_Click(object sender,RoutedEventArgs e){if(_selected is null)return;if(!File.Exists(_selected.StoredPath)){ShowError("Belge dosyası bulunamadı.");return;}Process.Start(new ProcessStartInfo(_selected.StoredPath){UseShellExecute=true});}
 private void Archive_Click(object sender,RoutedEventArgs e){if(_selected is null)return;_service.SetArchived(_selected.Id,!_selected.IsArchived);New_Click(sender,e);LoadData();}
 private void SelectCategory(string value){foreach(ComboBoxItem item in CategoryBox.Items)if(item.Content.ToString()==value){CategoryBox.SelectedItem=item;break;}}
 private void ShowError(string message){ErrorText.Text=message;ErrorText.Visibility=Visibility.Visible;}
}
