using System.Globalization;using System.Windows;using System.Windows.Controls;using IKDex.Models;using IKDex.Services;
namespace IKDex.Views;
public partial class PayrollPage:UserControl
{
 private readonly PayrollService _service=new(App.Database);private PayrollRecord? _selected;
 public PayrollPage(){InitializeComponent();EmployeeBox.ItemsSource=new EmployeeService(App.Database).GetAll();PeriodPicker.SelectedDate=new DateTime(DateTime.Today.Year,DateTime.Today.Month,1);New_Click(this,new RoutedEventArgs());LoadData();}
 private DateTime Period=>PeriodPicker.SelectedDate??DateTime.Today;
 private void LoadData(){var rows=_service.GetMonth(Period);PayrollGrid.ItemsSource=rows;var summary=_service.GetSummary(Period);SummaryText.Text=$"{Period:MMMM yyyy} • {summary.Count} bordro • Net toplam {summary.Net:N2} ₺";}
 private void PeriodChanged(object sender,SelectionChangedEventArgs e){if(IsLoaded){New_Click(sender,new RoutedEventArgs());LoadData();}}
 private void New_Click(object sender,RoutedEventArgs e){_selected=null;PayrollGrid.SelectedItem=null;FormTitle.Text="Yeni bordro";EmployeeBox.IsEnabled=true;EmployeeBox.SelectedItem=null;foreach(var box in AmountBoxes())box.Text="0";NotesBox.Clear();SaveButton.IsEnabled=true;StatusButtons.Visibility=Visibility.Collapsed;ErrorText.Visibility=Visibility.Collapsed;}
 private void PayrollGrid_SelectionChanged(object sender,SelectionChangedEventArgs e){if(PayrollGrid.SelectedItem is not PayrollRecord p)return;_selected=p;FormTitle.Text=$"{p.EmployeeName} bordrosu";EmployeeBox.SelectedValue=p.EmployeeId;EmployeeBox.IsEnabled=false;GrossBox.Text=Format(p.GrossSalary);BonusBox.Text=Format(p.Bonus);OvertimeBox.Text=Format(p.OvertimePay);SocialBox.Text=Format(p.SocialSecurityDeduction);UnemploymentBox.Text=Format(p.UnemploymentDeduction);IncomeTaxBox.Text=Format(p.IncomeTax);StampTaxBox.Text=Format(p.StampTax);OtherBox.Text=Format(p.OtherDeduction);NotesBox.Text=p.Notes;SaveButton.IsEnabled=p.Status=="Taslak";StatusButtons.Visibility=p.Status=="Ödendi"?Visibility.Collapsed:Visibility.Visible;AmountChanged(sender,new TextChangedEventArgs(TextBox.TextChangedEvent,UndoAction.None));}
 private void Save_Click(object sender,RoutedEventArgs e){if(EmployeeBox.SelectedValue is not long employeeId){ShowError("Personel seçin.");return;}if(!TryReadAmounts(out var values)){ShowError("Tutar alanlarına geçerli, negatif olmayan sayılar girin.");return;}var p=_selected??new PayrollRecord();p.EmployeeId=employeeId;p.Period=new DateTime(Period.Year,Period.Month,1);p.GrossSalary=values[0];p.Bonus=values[1];p.OvertimePay=values[2];p.SocialSecurityDeduction=values[3];p.UnemploymentDeduction=values[4];p.IncomeTax=values[5];p.StampTax=values[6];p.OtherDeduction=values[7];p.Notes=NotesBox.Text;try{_service.Save(p);New_Click(sender,e);LoadData();}catch(InvalidOperationException ex){ShowError(ex.Message);}}
 private void Approve_Click(object sender,RoutedEventArgs e){if(_selected is null||_selected.Status!="Taslak")return;_service.SetStatus(_selected.Id,"Onaylandı");New_Click(sender,e);LoadData();}
 private void Paid_Click(object sender,RoutedEventArgs e){if(_selected is null||_selected.Status!="Onaylandı"){ShowError("Yalnızca onaylanmış bordro ödendi olarak işaretlenebilir.");return;}_service.SetStatus(_selected.Id,"Ödendi");New_Click(sender,e);LoadData();}
 private void AmountChanged(object sender,TextChangedEventArgs e){if(NetSalaryText is null||!TryReadAmounts(out var v))return;var earnings=v[0]+v[1]+v[2];var deductions=v[3]+v[4]+v[5]+v[6]+v[7];NetSalaryText.Text=$"{earnings-deductions:N2} ₺";TotalDeductionText.Text=$"{deductions:N2} ₺";}
 private bool TryReadAmounts(out decimal[] values){values=new decimal[8];var boxes=AmountBoxes().ToArray();for(var i=0;i<boxes.Length;i++)if(!decimal.TryParse(boxes[i].Text,NumberStyles.Number,CultureInfo.CurrentCulture,out values[i])||values[i]<0)return false;return true;}
 private IEnumerable<TextBox> AmountBoxes()=>new[]{GrossBox,BonusBox,OvertimeBox,SocialBox,UnemploymentBox,IncomeTaxBox,StampTaxBox,OtherBox};private static string Format(decimal value)=>value.ToString("0.##");private void ShowError(string message){ErrorText.Text=message;ErrorText.Visibility=Visibility.Visible;}
}
